feat: allow to configure gateway.resources
apache/apisix-helm-chart pull request #694
Opened 2024-01-09 16:11 UTC by mstefany

Currently, if `gateway` deployment is enabled, then the `apisix` gateway container in the pod is deployed without any resource requests or limits, and they are not even configurable. This PR tries to make them configurable.

2024-01-16 15:56 UTC, Revolyssup approved these changes

2024-01-16 15:56 UTC, Revolyssup commented
please fix ci

2024-01-16 15:56 UTC, Revolyssup requested changes
please fix ci

2024-01-17 02:32 UTC, AlinsRan approved these changes

2024-01-18 10:15 UTC, zll600 commented
@Revolyssup  the ci has passed. Shall we merge this pr?

2024-01-21 13:58 UTC, Revolyssup approved these changes

2024-01-21 13:58 UTC, Revolyssup commented
@mstefany looks like there are few merge conflicts

2024-01-23 21:32 UTC, mstefany commented
@Revolyssup conflict is resolved, there was a collision with recently merged securityContext PR.

2024-01-24 06:14 UTC, merged